playground/202308/calculator.py
divide 함수 구현 (0으로 나누는 경우 고려 X)
=> 지수: divide 구현

.idea/.gitignore, .idea/misc.xml, .idea/modules.xml, .idea/study-git.iml, .idea/vcs.xml, git-basics/.idea/workspace.xml, playground/calculator.py
=> 지은: 더하기 기능 구현

playground/calculator.py
=> multiply-jinSeoHyun

playground/calculator.py
해결한 버그
리팩토링 내역
리뷰어에게 전하는 말 등
<br>
=> Feature [sub]

playground/calculator.py
=> Feature divdie

playground/calculator.py
=> Feature multiply

playground/calculator.py
=> feat: add 기능추가

git-basics/README-JinSeoHyun.md
=> Step 1 jin seo hyun

git-basics/README-LeeJisu.md
해결한 버그
리팩토링 내역
리뷰어에게 전하는 말 등
<br>
=> LeeJisu step-1 완료

playground/calculator.py
=> Feature subtract

playground/calculator.py
빼기 기능 추가
해결한 버그
리팩토링 내역
리뷰어에게 전하는 말 등
<br>
=> Feat subtract

playground/calculator.py
=> Feature add

playground/calculator.py
=> feat:multiply

playground/calculator.py
calculator의 divide 기능 구현
해결한 버그
리팩토링 내역
리뷰어에게 전하는 말 등
<br>
=> Feature divide

playground/calculator.py
=> added multiply

playground/calculator.py
=> Step 2 cha gi eun

playground/calculator.py
=> Feature 나누기

playground/calculator.py
해결한 버그
리팩토링 내역
리뷰어에게 전하는 말 등
<br>
=> feat:pow,abs,mod

playground/calculator.py
=> feature abs구현

git-basics/README-kangsumin.md
git-basics의 README-kangsumin.md 작성 완료
=> Step 1 kangsumin

git-basics/README-yongjin.md
=> 2024.03.17

playground/calculator.py
해결한 버그
리팩토링 내역
리뷰어에게 전하는 말 등
<br>
close #111 
=> feat: 1조 장원석 add 구현
